### ISSUE TITLE
Suggest correct game names

### ISSUE THREAD

**Issue by benjamin-musil** [adamdavies001/isthereanydeal-lookup#3]
Bot returns a name suggestion or a hyperlink to use command with the suggested game because ITAD doesn't have a perfect record of game names and the game id name has to exactly match right now.

For example
```!deals the forest``` can return ```"No games found for "the forest", here are some alternatives: "theforest" "someothergamewithforest"```

Another example is _Resident Evil 2_ needing the long form _RESIDENT EVIL 2 / BIOHAZARD RE:2 Standard Edition_ to register.

**Comment by adamdavies001** [comment]
This can be done with the [/v01/search/search](https://itad.docs.apiary.io/#reference/search/search/find-games) endpoint which will return a list of similar games (including IDs and proper names) based on the query.
